### PR TITLE
Update Build dependencies

### PR DESCRIPTION
**Pull request by herrwusel**
I think the libjson package is wrong. At least it is for ubuntu/raspbian

### CODE REVIEW

**Comment by christf** [comment]
Indeed:
```
ii  libjson-c-dev:armhf             0.12.1-1.1                           armhf        JSON manipulation library - development files
ii  libjson-c3:armhf                0.12.1-1.1                           armhf        JSON manipulation library - shared library
```

**Comment by christf** [comment]
Thank you for your contribution!

**Comment by herrwusel** [comment]
Kein Problem. Das ist aber auch so ziemlich alles, was ich kann.. Bist du in einem IRC channel oder hast du xmpp?

**Comment by herrwusel** [comment]
No problem. This is the only stuff I can do though :/. Are you in an irc channel/xmpp?

**Pull request merged**
