### PR TITLE
WIP add systemd initscript and configuration

### PR DESCRIPTION
**Pull request by christf**
it is nice to be able to initialize snapcastc.

- [ ] install init scripts by debian package

### CODE REVIEW

**Comment by christf** [comment]
this should help with #20

**Comment by jreusch** [comment]
hey hey
two small comments:
systemd services files which are shipped should not go to /etc/systemd/systemd/... but rather /lib/systemd/system/...

luckily all this can be done by debhelper, just put the respective service files in the debian folder and let dh_systemd do the rest.

if you like i could adapt this PR to this?

and another question:
it seems snapcastc (as all the other solutions in this area) have one server and one client binary.
but i see only one package in control.
wouldn't it be better to split those into separat packages? (and by thus removing some additional settings for dh_systemd)

**Comment by christf** [comment]
Hey,

On Sat, Jan 11, 2020 at 03:30:21AM -0800, jreusch wrote:
>hey hey
>two small comments:
>systemd services files which are shipped should not go to /etc/systemd/systemd/... but rather /lib/systemd/system/...
>
>luckily all this can be done by debhelper, just put the respective service files in the debian folder and let dh_systemd do the rest.
>
>if you like i could adapt this PR to this?
Sure! Thank you for the initiative!


>and another question:
>it seems snapcastc (as all the other solutions in this area) have one server and one client binary.
>but i see only one package in control.
>wouldn't it be better to split those into separat packages? (and by thus removing some additional settings for dh_systemd)
It certainly would reduce the footprint if just a client or server is 
needed. The build already has separate targets but the packaging does 
not reflect that yet.

**Comment by christf** [comment]
this is obsoleted by #45

**Pull request closed without merging**
